// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BlinkController from "./blink_controller"
application.register("blink", BlinkController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
